### ISSUE TITLE
URL template error keys

### ISSUE THREAD

**Issue by atdfairfax** [saclark/jekyll-multipost#7]
Hi, I am receiving the following error from Jekyll when I customise the prettylink template using `:layout` as per your example.

Code:

`permalink: ":layout/:categories/:title/"`

Error:

`jekyll 3.8.2 | Error:  The URL template doesn't have layout keys. Check your permalink template!`

Any ideas at all as to what I can do? Thanks.

**Comment by katcaola** [comment]
I have this issue too. Is this because Jekyll is now on v4.0?

Running `jekyll build --trace` shows the following:
```
mac:Blog katc$ jekyll build --trace
Configuration file: /Users/katc/jekyll/Blog/_config.yml
            Source: /Users/katc/jekyll/Blog
       Destination: /Users/katc/jekyll/Blog/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Traceback (most recent call last):
	39: from /Users/katc/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	38: from /Users/katc/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	37: from /Users/katc/.rvm/gems/ruby-2.6.3/bin/jekyll:23:in `<main>'
	36: from /Users/katc/.rvm/gems/ruby-2.6.3/bin/jekyll:23:in `load'
	35: from /Users/katc/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
	34: from /Users/katc/.rvm/gems/ruby-2.6.3/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	33: from /Users/katc/.rvm/gems/ruby-2.6.3/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	32: from /Users/katc/.rvm/gems/ruby-2.6.3/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	31: from /Users/katc/.rvm/gems/ruby-2.6.3/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	30: from /Users/katc/.rvm/gems/ruby-2.6.3/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	29: from /Users/katc/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	28: from /Users/katc/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
	27: from /Users/katc/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `each'
	26: from /Users/katc/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
	25: from /Users/katc/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:36:in `process'
	24: from /Users/katc/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:65:in `build'
	23: from /Users/katc/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/command.rb:28:in `process_site'
	22: from /Users/katc/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/site.rb:75:in `process'
	21: from /Users/katc/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/site.rb:183:in `generate'
	20: from /Users/katc/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/site.rb:183:in `each'
	19: from /Users/katc/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/site.rb:185:in `block in generate'
	18: from /Users/katc/jekyll/Blog/_plugins/multipost.rb:83:in `generate'
	17: from /Users/katc/jekyll/Blog/_plugins/multipost.rb:52:in `generate'
	16: from /Users/katc/jekyll/Blog/_plugins/multipost.rb:52:in `each'
	15: from /Users/katc/jekyll/Blog/_plugins/multipost.rb:53:in `block in generate'
	14: from /Users/katc/jekyll/Blog/_plugins/multipost.rb:53:in `map!'
	13: from /Users/katc/jekyll/Blog/_plugins/multipost.rb:55:in `block (2 levels) in generate'
	12: from /Users/katc/jekyll/Blog/_plugins/multipost.rb:68:in `create_layout_views'
	11: from /Users/katc/jekyll/Blog/_plugins/multipost.rb:68:in `map'
	10: from /Users/katc/jekyll/Blog/_plugins/multipost.rb:69:in `block in create_layout_views'
	 9: from /Users/katc/jekyll/Blog/_plugins/multipost.rb:69:in `tap'
	 8: from /Users/katc/jekyll/Blog/_plugins/multipost.rb:72:in `block (2 levels) in create_layout_views'
	 7: from /Users/katc/jekyll/Blog/_plugins/multipost.rb:9:in `get_adjusted_permalink'
	 6: from /Users/katc/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/document.rb:243:in `url'
	 5: from /Users/katc/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/url.rb:39:in `to_s'
	 4: from /Users/katc/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/url.rb:46:in `generated_permalink'
	 3: from /Users/katc/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/url.rb:62:in `generate_url'
	 2: from /Users/katc/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/url.rb:96:in `generate_url_from_drop'
	 1: from /Users/katc/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/url.rb:96:in `gsub'
/Users/katc/.rvm/gems/ruby-2.6.3/gems/jekyll-4.0.0/lib/jekyll/url.rb:101:in `block in generate_url_from_drop': The URL template doesn't have layout keys. Check your permalink template! (NoMethodError)
```
